name: Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Invoke workflow without inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Message Echo 1222
        token: ${{ secrets.GITHUB_TOKEN }}
        inputs: '{"message": "blah blah"}'
