name: Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Invoke echo 1 workflow using this action
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Message Echo 1
        token: ${{ secrets.DISPATCH_TOKEN }}
        inputs: '{"message": "blah blah"}'

    - name: Invoke external workflow using this action
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: e2e
        token: ${{ secrets.DISPATCH_TOKEN }}
        repo: Nested-Innovation/MomentumE2E
        inputs: '{"env": "erp"}'
        ref: master
